### ISSUE TITLE
Data Download Link Not Received

### ISSUE THREAD

**Issue by BetterZH** [Tianwei3989/apolo#2]
Hi,  I have been closely following your work and am very interested in exploring the concepts discussed in your recent paper.  I submitted an application for the APOLO Dataset, but I have **not** yet received the download link.

 I would be grateful if you could update me on the status of my application. Thank you for your prompt attention to this matter.

**Comment by Tianwei3989** [comment]
Hi, thanks for your message.
I'm sorry that I didn't receive any notification from the system.
If you haven't seen any reply, could you please send another application form or a direct message to my email (chentw[at]XXX)?
We will reply to the request as soon as we find it.
Best regards

**Comment by BetterZH** [comment]
> Hi, thanks for your message. I'm sorry that I didn't receive any notification from the system. If you haven't seen any reply, could you please send another application form or a direct message to my email (chentw[at]XXX)? We will reply to the request as soon as we find it. Best regards

Thank you for the update! I have received the data share successfully.
