### ISSUE TITLE
Question regarding mismatch in artemis_id between apolo.json and artemis_dataset_release_v0.csv

### ISSUE THREAD

**Issue by BetterZH** [Tianwei3989/apolo#3]
I encountered an issue with the **'artemis_id'** in both the **apolo.json'** file and the **'artemis_dataset_release_v0.csv** file. 

According to the Dataset Preparation instructions, I downloaded the artemis_dataset_release_v0.csv file from https://www.artemisdataset.org/#dataset. However, during steps 8 and 9, I found the following issues:

1. The total number of data entries in the artemis_dataset_release_v0.csv file is 454,677, but the artemis_id in the apolo/artemis_index/train_index.json file contains **IDs that exceed this range, such as 454,682 and 454,681**. Could this be a mistake, or is there an explanation for why these IDs are out of range?
<img width="522" alt="image" src="https://github.com/user-attachments/assets/2822136d-887e-4e25-8d46-a43357e750df">
<img width="911" alt="image" src="https://github.com/user-attachments/assets/a029589f-4183-4bfb-ba71-f5b6f1a0d3d5">

2. I have added code (highlighted in the **red box** in the image below) to perform the matching check. I found that **nearly 30% of the data (1,728 entries) in the apolo.json file has artemis_id values that do not match their corresponding positions in the artemis_dataset_release_v0.csv file.** This discrepancy has me quite confused—could you kindly help confirm if this is expected, or if there may be an issue with the ID assignment?

<img width="898" alt="1f8ead9ba49d3a3804353d760b12cca" src="https://github.com/user-attachments/assets/3ddd2980-70ab-473c-9110-87449fffa140">
<img width="712" alt="9558f168fda874af5c5187d411abab1" src="https://github.com/user-attachments/assets/09b045f4-b391-4067-a112-3f35b0b178d0">

I would greatly appreciate any guidance on how to resolve these discrepancies. 

Thank you very much for your help!

**Comment by Tianwei3989** [comment]
Hi, I checked the ```apolo.json``` on my end and did not find the error.
The version of ```artemis_dataset_release_v0.csv``` of mine contains 454684 samples, and thus the out-of-index error did not occur.
![image](https://github.com/user-attachments/assets/6b4b2c84-8d67-4ccf-8bae-a8656160c662)

I also checked the painting names, and they all matched.
![image](https://github.com/user-attachments/assets/afc55491-8501-461b-89ef-3f1b976b1f17)


Hummm... would there be some missing samples in the new version of ```artemis_dataset_release_v0.csv```...?

**Comment by Tianwei3989** [comment]
Hi, I request a new version of ```artemis_dataset_release_v0.csv``` from [https://www.artemisdataset.org/#dataset](https://www.artemisdataset.org/#dataset) and find that they have exactly the same amount of samples as I had (454684 samples).

The code returns the same result as I got in the last comment.

Can you check the file on your end or request a new version of ```artemis_dataset_release_v0.csv```?

**Comment by BetterZH** [comment]
> Hi, I request a new version of `artemis_dataset_release_v0.csv` from https://www.artemisdataset.org/#dataset and find that they have exactly the same amount of samples as I had (454684 samples).
> 
> The code returns the same result as I got in the last comment.
> 
> Can you check the file on your end or request a new version of `artemis_dataset_release_v0.csv`?

Thank you for your reply! I would like to confirm, did you apply for the zip dataset by filling out [this form](https://docs.google.com/forms/d/e/1FAIpQLScmq5Ob4v2VNLHqPpo7CAh81v_uRW_Kkwqmd0NTcS6nu1vMYg/viewform)?

**Comment by BetterZH** [comment]
The issue has been resolved, and the data is indeed correct. I had previously opened the file in Excel, and sometimes opening a CSV file in Excel can cause automatic adjustments to encoding or formatting, which can affect the accuracy of the data. Thank you very much for your help!
