### ISSUE TITLE
apolo.json

### ISSUE THREAD

**Issue by XinyuWang66** [Tianwei3989/apolo#5]
Hello，
**question 1：**![apolo](https://github.com/user-attachments/assets/ccbeb4b4-e455-4ecb-91a8-5afbdd3e7b9e)
**My apolo.json file doesn't have an emotion column.**
![4](https://github.com/user-attachments/assets/d96a27ef-94a5-4b07-b86d-e91ad00d7ca8)
**question 2：**
![c](https://github.com/user-attachments/assets/5cb02402-bf5c-4436-a725-7b89b498236c)
![9](https://github.com/user-attachments/assets/6ee5b766-f1be-4ee6-a9fb-b3d3b2d4231a)

**I wanted to ask where the train.csv file was, I didn't find it.**

**Comment by Tianwei3989** [comment]
Hi, please follow [the instructions for dataset preparation](https://github.com/Tianwei3989/apolo/tree/main#dataset-preparation).
You will find them after the process.
